// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests.CheckPeriodClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class CheckPeriod
    {
        
        /// <summary>
        /// ChooseDates - Используйте "ChooseDatesParams" для передачи параметров в этот метод.
        /// </summary>
        public void ChooseDates()
        {
            #region Variable Declarations
            WpfDatePicker uIDateStartDatePicker = this.UIBankSystemWindow.UIDateStartDatePicker;
            WpfDatePicker uIDateEndDatePicker = this.UIBankSystemWindow.UIDateEndDatePicker;
            #endregion

            // Выберите "01-Dec-2017" в "dateStart" Выбор даты
            uIDateStartDatePicker.DateAsString = this.ChooseDatesParams.UIDateStartDatePickerDateAsString;

            // Выберите "01-Dec-2018" в "dateEnd" Выбор даты
            uIDateEndDatePicker.DateAsString = this.ChooseDatesParams.UIDateEndDatePickerDateAsString;
        }
        
        /// <summary>
        /// ClickButtonFormPeriod
        /// </summary>
        public void ClickButtonFormPeriod()
        {
            #region Variable Declarations
            WpfButton uIУстановитьдиапозондаButton = this.UIBankSystemWindow.UIУстановитьдиапозондаButton;
            #endregion

            // Щелкните "Установить диапозон дат" кнопка
            Mouse.Click(uIУстановитьдиапозондаButton, new Point(99, 56));
        }
        
        /// <summary>
        /// LabelPeriodClick
        /// </summary>
        public void LabelPeriodClick()
        {
            #region Variable Declarations
            WpfText uIСуммазавесьуказанныйText = this.UIBankSystemWindow.UIСуммазавесьуказанныйText;
            #endregion

            // Щелкните "Сумма за весь указанный период: 13150 . Сумма за п..." надпись
            Mouse.Click(uIСуммазавесьуказанныйText, new Point(412, 22));
        }
        
        /// <summary>
        /// AssertResult - Используйте "AssertResultExpectedValues" для передачи параметров в этот метод.
        /// </summary>
        public void AssertResult()
        {
            #region Variable Declarations
            WpfText uIСуммазавесьуказанныйText = this.UIBankSystemWindow.UIСуммазавесьуказанныйText;
            #endregion

            // Убедитесь, что свойство FriendlyName "Сумма за весь указанный период: 13150 . Сумма за п..." надпись равняется "Сумма за весь указанный период: 13150 . Сумма за п..."
            Assert.AreEqual(this.AssertResultExpectedValues.UIСуммазавесьуказанныйTextFriendlyName, uIСуммазавесьуказанныйText.FriendlyName, "Сумма за весь указанный период: 13150 . Сумма за п...");
        }
        
        #region Properties
        public virtual ChooseDatesParams ChooseDatesParams
        {
            get
            {
                if ((this.mChooseDatesParams == null))
                {
                    this.mChooseDatesParams = new ChooseDatesParams();
                }
                return this.mChooseDatesParams;
            }
        }
        
        public virtual AssertResultExpectedValues AssertResultExpectedValues
        {
            get
            {
                if ((this.mAssertResultExpectedValues == null))
                {
                    this.mAssertResultExpectedValues = new AssertResultExpectedValues();
                }
                return this.mAssertResultExpectedValues;
            }
        }
        
        public UIBankSystemWindow UIBankSystemWindow
        {
            get
            {
                if ((this.mUIBankSystemWindow == null))
                {
                    this.mUIBankSystemWindow = new UIBankSystemWindow();
                }
                return this.mUIBankSystemWindow;
            }
        }
        #endregion
        
        #region Fields
        private ChooseDatesParams mChooseDatesParams;
        
        private AssertResultExpectedValues mAssertResultExpectedValues;
        
        private UIBankSystemWindow mUIBankSystemWindow;
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "ChooseDates"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class ChooseDatesParams
    {
        
        #region Fields
        /// <summary>
        /// Выберите "01-Dec-2017" в "dateStart" Выбор даты
        /// </summary>
        public string UIDateStartDatePickerDateAsString = "01-Dec-2017";
        
        /// <summary>
        /// Выберите "01-Dec-2018" в "dateEnd" Выбор даты
        /// </summary>
        public string UIDateEndDatePickerDateAsString = "01-Dec-2018";
        #endregion
    }
    
    /// <summary>
    /// Параметры для передачи в "AssertResult"
    /// </summary>
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class AssertResultExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Убедитесь, что свойство FriendlyName "Сумма за весь указанный период: 13150 . Сумма за п..." надпись равняется "Сумма за весь указанный период: 13150 . Сумма за п..."
        /// </summary>
        public string UIСуммазавесьуказанныйTextFriendlyName = "Сумма за весь указанный период: 13150 . Сумма за п...";
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow : WpfWindow
    {
        
        public UIBankSystemWindow()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfDatePicker UIDateStartDatePicker
        {
            get
            {
                if ((this.mUIDateStartDatePicker == null))
                {
                    this.mUIDateStartDatePicker = new WpfDatePicker(this);
                    #region Условия поиска
                    this.mUIDateStartDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "dateStart";
                    this.mUIDateStartDatePicker.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIDateStartDatePicker;
            }
        }
        
        public WpfDatePicker UIDateEndDatePicker
        {
            get
            {
                if ((this.mUIDateEndDatePicker == null))
                {
                    this.mUIDateEndDatePicker = new WpfDatePicker(this);
                    #region Условия поиска
                    this.mUIDateEndDatePicker.SearchProperties[WpfDatePicker.PropertyNames.AutomationId] = "dateEnd";
                    this.mUIDateEndDatePicker.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIDateEndDatePicker;
            }
        }
        
        public WpfButton UIУстановитьдиапозондаButton
        {
            get
            {
                if ((this.mUIУстановитьдиапозондаButton == null))
                {
                    this.mUIУстановитьдиапозондаButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIУстановитьдиапозондаButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "dateButton";
                    this.mUIУстановитьдиапозондаButton.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIУстановитьдиапозондаButton;
            }
        }
        
        public WpfText UIСуммазавесьуказанныйText
        {
            get
            {
                if ((this.mUIСуммазавесьуказанныйText == null))
                {
                    this.mUIСуммазавесьуказанныйText = new WpfText(this);
                    #region Условия поиска
                    this.mUIСуммазавесьуказанныйText.SearchProperties[WpfText.PropertyNames.AutomationId] = "resultForPeriodTextBlock";
                    this.mUIСуммазавесьуказанныйText.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIСуммазавесьуказанныйText;
            }
        }
        #endregion
        
        #region Fields
        private WpfDatePicker mUIDateStartDatePicker;
        
        private WpfDatePicker mUIDateEndDatePicker;
        
        private WpfButton mUIУстановитьдиапозондаButton;
        
        private WpfText mUIСуммазавесьуказанныйText;
        #endregion
    }
}
