// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests.maps.EqualNumberOfRowsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class EqualNumberOfRows
    {
        
        /// <summary>
        /// ReturnToAllListButtonClicked
        /// </summary>
        public void ReturnToAllListButtonClicked()
        {
            #region Variable Declarations
            WpfButton uIПоказатьсписокButton = this.UIBankSystemWindow.UIПоказатьсписокButton;
            #endregion

            // Щелкните "Показать список" кнопка
            Mouse.Click(uIПоказатьсписокButton, new Point(158, 16));
        }
        
        /// <summary>
        /// AllListClicked
        /// </summary>
        public void AllListClicked()
        {
            #region Variable Declarations
            WpfTable uIRecordsGridTable = this.UIBankSystemWindow.UIRecordsGridTable;
            #endregion

            // Щелкните "recordsGrid" таблица
            Mouse.Click(uIRecordsGridTable, new Point(9, 23));
        }
        
        /// <summary>
        /// AssertListOfRecordsNotNull
        /// </summary>
        public void AssertListOfRecordsNotNull()
        {
            #region Variable Declarations
            WpfTable uIRecordsGridTable = this.UIBankSystemWindow.UIRecordsGridTable;
            #endregion

            // Убедитесь, что свойство RowCount "recordsGrid" таблица не совпадает с "null"
            Assert.IsNotNull(uIRecordsGridTable.RowCount);
        }
        
        #region Properties
        public UIBankSystemWindow UIBankSystemWindow
        {
            get
            {
                if ((this.mUIBankSystemWindow == null))
                {
                    this.mUIBankSystemWindow = new UIBankSystemWindow();
                }
                return this.mUIBankSystemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBankSystemWindow mUIBankSystemWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow : WpfWindow
    {
        
        public UIBankSystemWindow()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfTable UIRecordsGridTable
        {
            get
            {
                if ((this.mUIRecordsGridTable == null))
                {
                    this.mUIRecordsGridTable = new WpfTable(this);
                    #region Условия поиска
                    this.mUIRecordsGridTable.SearchProperties[WpfTable.PropertyNames.AutomationId] = "recordsGrid";
                    this.mUIRecordsGridTable.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIRecordsGridTable;
            }
        }
        
        public WpfButton UIПоказатьсписокButton
        {
            get
            {
                if ((this.mUIПоказатьсписокButton == null))
                {
                    this.mUIПоказатьсписокButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIПоказатьсписокButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "returnToStartListButton";
                    this.mUIПоказатьсписокButton.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIПоказатьсписокButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfTable mUIRecordsGridTable;
        
        private WpfButton mUIПоказатьсписокButton;
        #endregion
    }
}
