// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests.maps.ScrollListClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class ScrollList
    {
        
        /// <summary>
        /// ScrollDown
        /// </summary>
        public void ScrollDown()
        {
            #region Variable Declarations
            WpfTable uIRecordsGridTable = this.UIBankSystemWindow.UIRecordsGridTable;
            #endregion

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1351, 541));

            // Щелкните "recordsGrid" таблица
            Mouse.Click(uIRecordsGridTable, new Point(1351, 541));
        }
        
        /// <summary>
        /// WindowHide
        /// </summary>
        public void WindowHide()
        {
            #region Variable Declarations
            WinButton uIСвернутьButton = this.UIBankSystemWindow1.UIСвернутьButton;
            #endregion

            // Щелкните "Свернуть" кнопка
            Mouse.Click(uIСвернутьButton, new Point(47, 21));
        }
        
        /// <summary>
        /// ScrollUp
        /// </summary>
        public void ScrollUp()
        {
            #region Variable Declarations
            WpfTable uIRecordsGridTable = this.UIBankSystemWindow.UIRecordsGridTable;
            #endregion

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1355, 72));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1354, 73));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1354, 73));

            // Щелкните "recordsGrid" таблица
            Mouse.Click(uIRecordsGridTable, new Point(1354, 73));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));

            // Двойной щелчок "recordsGrid" таблица
            Mouse.DoubleClick(uIRecordsGridTable, new Point(1353, 64));
        }
        
        #region Properties
        public UIBankSystemWindow UIBankSystemWindow
        {
            get
            {
                if ((this.mUIBankSystemWindow == null))
                {
                    this.mUIBankSystemWindow = new UIBankSystemWindow();
                }
                return this.mUIBankSystemWindow;
            }
        }
        
        public UIBankSystemWindow1 UIBankSystemWindow1
        {
            get
            {
                if ((this.mUIBankSystemWindow1 == null))
                {
                    this.mUIBankSystemWindow1 = new UIBankSystemWindow1();
                }
                return this.mUIBankSystemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIBankSystemWindow mUIBankSystemWindow;
        
        private UIBankSystemWindow1 mUIBankSystemWindow1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow : WpfWindow
    {
        
        public UIBankSystemWindow()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfTable UIRecordsGridTable
        {
            get
            {
                if ((this.mUIRecordsGridTable == null))
                {
                    this.mUIRecordsGridTable = new WpfTable(this);
                    #region Условия поиска
                    this.mUIRecordsGridTable.SearchProperties[WpfTable.PropertyNames.AutomationId] = "recordsGrid";
                    this.mUIRecordsGridTable.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIRecordsGridTable;
            }
        }
        #endregion
        
        #region Fields
        private WpfTable mUIRecordsGridTable;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow1 : WinWindow
    {
        
        public UIBankSystemWindow1()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WinButton UIСвернутьButton
        {
            get
            {
                if ((this.mUIСвернутьButton == null))
                {
                    this.mUIСвернутьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIСвернутьButton.SearchProperties[WinButton.PropertyNames.Name] = "Свернуть";
                    this.mUIСвернутьButton.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIСвернутьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIСвернутьButton;
        #endregion
    }
}
