// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests.maps.SortListClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class SortList
    {
        
        /// <summary>
        /// Sort
        /// </summary>
        public void Sort()
        {
            #region Variable Declarations
            WinTitleBar uIBankSystemTitleBar = this.UIBankSystemWindow.UIBankSystemTitleBar;
            WpfControl uIНазваниеоперацииColumnHeader = this.UIBankSystemWindow1.UIRecordsGridTable.UIPART_ColumnHeadersPrHeader.UIНазваниеоперацииColumnHeader;
            WpfText uIСуммаText = this.UIBankSystemWindow1.UIRecordsGridTable.UIPART_ColumnHeadersPrHeader.UIСуммаColumnHeader.UIСуммаText;
            WpfControl uIДатаColumnHeader = this.UIBankSystemWindow1.UIRecordsGridTable.UIPART_ColumnHeadersPrHeader.UIДатаColumnHeader;
            WpfText uIОперацияпоступленияText = this.UIBankSystemWindow1.UIRecordsGridTable.UIPART_ColumnHeadersPrHeader.UIОперацияпоступленияColumnHeader.UIОперацияпоступленияText;
            #endregion

            // Щелкните "BankSystem" название
            Mouse.Click(uIBankSystemTitleBar, new Point(325, 23));

            // Щелкните "Название операции" заголовок столбца
            Mouse.Click(uIНазваниеоперацииColumnHeader, new Point(256, 25));

            // Щелкните "Название операции" заголовок столбца
            Mouse.Click(uIНазваниеоперацииColumnHeader, new Point(256, 25));

            // Щелкните "Сумма" надпись
            Mouse.Click(uIСуммаText, new Point(60, 15));

            // Щелкните "Сумма" надпись
            Mouse.Click(uIСуммаText, new Point(64, 17));

            // Щелкните "Дата" заголовок столбца
            Mouse.Click(uIДатаColumnHeader, new Point(121, 34));

            // Щелкните "Дата" заголовок столбца
            Mouse.Click(uIДатаColumnHeader, new Point(121, 34));

            // Щелкните "Операция поступления" надпись
            Mouse.Click(uIОперацияпоступленияText, new Point(113, 21));

            // Щелкните "Операция поступления" надпись
            Mouse.Click(uIОперацияпоступленияText, new Point(110, 21));
        }
        
        /// <summary>
        /// WindowClose
        /// </summary>
        public void WindowClose()
        {
            #region Variable Declarations
            WinTitleBar uIBankSystemTitleBar = this.UIBankSystemWindow.UIBankSystemTitleBar;
            WinButton uIЗакрытьButton = this.UIBankSystemWindow.UIЗакрытьButton;
            #endregion

            // Щелкните "BankSystem" название
            Mouse.Click(uIBankSystemTitleBar, new Point(208, 25));

            // Щелкните "Закрыть" кнопка
            Mouse.Click(uIЗакрытьButton, new Point(55, 31));
        }
        
        #region Properties
        public UIBankSystemWindow UIBankSystemWindow
        {
            get
            {
                if ((this.mUIBankSystemWindow == null))
                {
                    this.mUIBankSystemWindow = new UIBankSystemWindow();
                }
                return this.mUIBankSystemWindow;
            }
        }
        
        public UIBankSystemWindow1 UIBankSystemWindow1
        {
            get
            {
                if ((this.mUIBankSystemWindow1 == null))
                {
                    this.mUIBankSystemWindow1 = new UIBankSystemWindow1();
                }
                return this.mUIBankSystemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIBankSystemWindow mUIBankSystemWindow;
        
        private UIBankSystemWindow1 mUIBankSystemWindow1;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow : WinWindow
    {
        
        public UIBankSystemWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIBankSystemTitleBar
        {
            get
            {
                if ((this.mUIBankSystemTitleBar == null))
                {
                    this.mUIBankSystemTitleBar = new WinTitleBar(this);
                    #region Условия поиска
                    this.mUIBankSystemTitleBar.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIBankSystemTitleBar;
            }
        }
        
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinTitleBar mUIBankSystemTitleBar;
        
        private WinButton mUIЗакрытьButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow1 : WpfWindow
    {
        
        public UIBankSystemWindow1()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public UIRecordsGridTable UIRecordsGridTable
        {
            get
            {
                if ((this.mUIRecordsGridTable == null))
                {
                    this.mUIRecordsGridTable = new UIRecordsGridTable(this);
                }
                return this.mUIRecordsGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIRecordsGridTable mUIRecordsGridTable;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIRecordsGridTable : WpfTable
    {
        
        public UIRecordsGridTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "recordsGrid";
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public UIPART_ColumnHeadersPrHeader UIPART_ColumnHeadersPrHeader
        {
            get
            {
                if ((this.mUIPART_ColumnHeadersPrHeader == null))
                {
                    this.mUIPART_ColumnHeadersPrHeader = new UIPART_ColumnHeadersPrHeader(this);
                }
                return this.mUIPART_ColumnHeadersPrHeader;
            }
        }
        #endregion
        
        #region Fields
        private UIPART_ColumnHeadersPrHeader mUIPART_ColumnHeadersPrHeader;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIPART_ColumnHeadersPrHeader : WpfControl
    {
        
        public UIPART_ColumnHeadersPrHeader(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "Header";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "PART_ColumnHeadersPresenter";
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfControl UIНазваниеоперацииColumnHeader
        {
            get
            {
                if ((this.mUIНазваниеоперацииColumnHeader == null))
                {
                    this.mUIНазваниеоперацииColumnHeader = new WpfControl(this);
                    #region Условия поиска
                    this.mUIНазваниеоперацииColumnHeader.SearchProperties[WpfControl.PropertyNames.ControlType] = "ColumnHeader";
                    this.mUIНазваниеоперацииColumnHeader.SearchProperties[WpfControl.PropertyNames.Name] = "Название операции";
                    this.mUIНазваниеоперацииColumnHeader.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIНазваниеоперацииColumnHeader;
            }
        }
        
        public UIСуммаColumnHeader UIСуммаColumnHeader
        {
            get
            {
                if ((this.mUIСуммаColumnHeader == null))
                {
                    this.mUIСуммаColumnHeader = new UIСуммаColumnHeader(this);
                }
                return this.mUIСуммаColumnHeader;
            }
        }
        
        public WpfControl UIДатаColumnHeader
        {
            get
            {
                if ((this.mUIДатаColumnHeader == null))
                {
                    this.mUIДатаColumnHeader = new WpfControl(this);
                    #region Условия поиска
                    this.mUIДатаColumnHeader.SearchProperties[WpfControl.PropertyNames.ControlType] = "ColumnHeader";
                    this.mUIДатаColumnHeader.SearchProperties[WpfControl.PropertyNames.Name] = "Дата";
                    this.mUIДатаColumnHeader.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIДатаColumnHeader;
            }
        }
        
        public UIОперацияпоступленияColumnHeader UIОперацияпоступленияColumnHeader
        {
            get
            {
                if ((this.mUIОперацияпоступленияColumnHeader == null))
                {
                    this.mUIОперацияпоступленияColumnHeader = new UIОперацияпоступленияColumnHeader(this);
                }
                return this.mUIОперацияпоступленияColumnHeader;
            }
        }
        #endregion
        
        #region Fields
        private WpfControl mUIНазваниеоперацииColumnHeader;
        
        private UIСуммаColumnHeader mUIСуммаColumnHeader;
        
        private WpfControl mUIДатаColumnHeader;
        
        private UIОперацияпоступленияColumnHeader mUIОперацияпоступленияColumnHeader;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIСуммаColumnHeader : WpfControl
    {
        
        public UIСуммаColumnHeader(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "ColumnHeader";
            this.SearchProperties[WpfControl.PropertyNames.Name] = "Сумма";
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfText UIСуммаText
        {
            get
            {
                if ((this.mUIСуммаText == null))
                {
                    this.mUIСуммаText = new WpfText(this);
                    #region Условия поиска
                    this.mUIСуммаText.SearchProperties[WpfText.PropertyNames.Name] = "Сумма";
                    this.mUIСуммаText.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIСуммаText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIСуммаText;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОперацияпоступленияColumnHeader : WpfControl
    {
        
        public UIОперацияпоступленияColumnHeader(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.SearchProperties[WpfControl.PropertyNames.ControlType] = "ColumnHeader";
            this.SearchProperties[WpfControl.PropertyNames.Name] = "Операция поступления";
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfText UIОперацияпоступленияText
        {
            get
            {
                if ((this.mUIОперацияпоступленияText == null))
                {
                    this.mUIОперацияпоступленияText = new WpfText(this);
                    #region Условия поиска
                    this.mUIОперацияпоступленияText.SearchProperties[WpfText.PropertyNames.Name] = "Операция поступления";
                    this.mUIОперацияпоступленияText.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIОперацияпоступленияText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIОперацияпоступленияText;
        #endregion
    }
}
