// ------------------------------------------------------------------------------
//  <auto-generated>
//      Этот код был создан построителем кодированных тестов ИП.
//      Версия: 15.0.0.0
//
//      Изменения, внесенные в этот файл, могут привести к неправильной работе кода и будут
//      утрачены при повторном формировании кода.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests.maps.TheWindowAppearsClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public partial class TheWindowAppears
    {
        
        /// <summary>
        /// AssertWindowOpend
        /// </summary>
        public void AssertWindowOpend()
        {
            #region Variable Declarations
            WinWindow uIОткрытиеWindow = this.UIОткрытиеWindow;
            #endregion

            // Убедитесь, что свойство Name "Открытие" окно не совпадает с "null"
            Assert.IsNotNull(uIОткрытиеWindow.Name, "Окно с выбором репозитория не открылось");
        }
        
        /// <summary>
        /// ButtonChooseRepositoryClicked
        /// </summary>
        public void ButtonChooseRepositoryClicked()
        {
            #region Variable Declarations
            WpfButton uIВыборрепозиторияButton = this.UIBankSystemWindow.UIВыборрепозиторияButton;
            #endregion

            // Щелкните "Выбор репозитория" кнопка
            Mouse.Click(uIВыборрепозиторияButton, new Point(71, 60));
        }
        
        /// <summary>
        /// WindowClosed
        /// </summary>
        public void WindowClosed()
        {
            #region Variable Declarations
            WinButton uIЗакрытьButton = this.UIОткрытиеWindow.UIОткрытиеTitleBar.UIЗакрытьButton;
            #endregion

            // Щелкните "Закрыть" кнопка
            Mouse.Click(uIЗакрытьButton, new Point(25, 27));
        }
        
        /// <summary>
        /// WindowOpened
        /// </summary>
        public void WindowOpened()
        {
            #region Variable Declarations
            WinTitleBar uIОткрытиеTitleBar = this.UIОткрытиеWindow.UIОткрытиеTitleBar;
            #endregion

            // Щелкните "Открытие" название
            Mouse.Click(uIОткрытиеTitleBar, new Point(574, 28));
        }
        
        #region Properties
        public UIBankSystemWindow UIBankSystemWindow
        {
            get
            {
                if ((this.mUIBankSystemWindow == null))
                {
                    this.mUIBankSystemWindow = new UIBankSystemWindow();
                }
                return this.mUIBankSystemWindow;
            }
        }
        
        public UIОткрытиеWindow UIОткрытиеWindow
        {
            get
            {
                if ((this.mUIОткрытиеWindow == null))
                {
                    this.mUIОткрытиеWindow = new UIОткрытиеWindow();
                }
                return this.mUIОткрытиеWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIBankSystemWindow mUIBankSystemWindow;
        
        private UIОткрытиеWindow mUIОткрытиеWindow;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIBankSystemWindow : WpfWindow
    {
        
        public UIBankSystemWindow()
        {
            #region Условия поиска
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "BankSystem";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("BankSystem");
            #endregion
        }
        
        #region Properties
        public WpfButton UIВыборрепозиторияButton
        {
            get
            {
                if ((this.mUIВыборрепозиторияButton == null))
                {
                    this.mUIВыборрепозиторияButton = new WpfButton(this);
                    #region Условия поиска
                    this.mUIВыборрепозиторияButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "changeRepositoryButton";
                    this.mUIВыборрепозиторияButton.WindowTitles.Add("BankSystem");
                    #endregion
                }
                return this.mUIВыборрепозиторияButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIВыборрепозиторияButton;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОткрытиеWindow : WinWindow
    {
        
        public UIОткрытиеWindow()
        {
            #region Условия поиска
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Открытие";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public UIОткрытиеTitleBar UIОткрытиеTitleBar
        {
            get
            {
                if ((this.mUIОткрытиеTitleBar == null))
                {
                    this.mUIОткрытиеTitleBar = new UIОткрытиеTitleBar(this);
                }
                return this.mUIОткрытиеTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIОткрытиеTitleBar mUIОткрытиеTitleBar;
        #endregion
    }
    
    [GeneratedCode("Построитель кодированных тестов ИП", "15.0.26208.0")]
    public class UIОткрытиеTitleBar : WinTitleBar
    {
        
        public UIОткрытиеTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Условия поиска
            this.WindowTitles.Add("Открытие");
            #endregion
        }
        
        #region Properties
        public WinButton UIЗакрытьButton
        {
            get
            {
                if ((this.mUIЗакрытьButton == null))
                {
                    this.mUIЗакрытьButton = new WinButton(this);
                    #region Условия поиска
                    this.mUIЗакрытьButton.SearchProperties[WinButton.PropertyNames.Name] = "Закрыть";
                    this.mUIЗакрытьButton.WindowTitles.Add("Открытие");
                    #endregion
                }
                return this.mUIЗакрытьButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIЗакрытьButton;
        #endregion
    }
}
